server:
  port: 9092

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/Java9TahminDB
    username: admin
    password:
  rabbitmq:
    enabled: true
    host: localhost
    port: 5672
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update

userservices:
  secrets:
    secret-key: ${JAVA9_SECRETKEY}
    issuer: ${JAVA9_ISSUER}